### ISSUE TITLE
Example log file

### ISSUE THREAD

**Issue by griffinpuc** [griffinpuc/tangenportalv2#23]
Request for example log file. For generating graphs for user to visualize data.

**Comment by bernpuc** [comment]
[LOG_CP10_08-06-19-08_19AM.txt](https://github.com/griffinpuc/tangenportalv2/files/3946320/LOG_CP10_08-06-19-08_19AM.txt)

**Comment by bernpuc** [comment]
The LOG file contains temperature measurements acquired during a test run. These measurements are used to determine proper operation of the instrument during development.

**Comment by griffinpuc** [comment]
Thanks.
