### ISSUE TITLE
Pageinated API call

### ISSUE THREAD

**Issue by griffinpuc** [griffinpuc/tangenportalv2#28]
Method for paginating API calls.
Maybe something like this:
call?min=100&max=120
or
call?min=110&max=top (gets upper limit, or lower limit if set)
call?min=bot&max=top (gets all)
call?min=bot&max=100

**Comment by bernpuc** [comment]
After a bit of searching, this seems to be a suitable scheme: https://www.moesif.com/blog/technical/api-design/REST-API-Design-Filtering-Sorting-and-Pagination/#offset-pagination

short answer: 
GET /items?limit=20
GET /items?limit=20&offset=20

**Comment by griffinpuc** [comment]
👍
