### ISSUE TITLE
Design sample run & raw files

### ISSUE THREAD

**Issue by griffinpuc** [griffinpuc/tangenportalv2#8]
Sample run files and raw result files. Use these samples to test instrument sim and webapp downloads.

**Comment by bernpuc** [comment]
You want a raw data file and a result data file?

**Comment by griffinpuc** [comment]
Yeah, the most recent version you have @bernpuc

**Comment by bernpuc** [comment]
Here is a Report Json File

[RSLT_20191126_172817_CPDEV2KRKKK.txt](https://github.com/griffinpuc/tangenportalv2/files/3897163/RSLT_20191126_172817_CPDEV2KRKKK.txt)

**Comment by bernpuc** [comment]
Here is a Raw Data File

[RUN_CPDEV2_11-26-19-05_28PM.txt](https://github.com/griffinpuc/tangenportalv2/files/3897181/RUN_CPDEV2_11-26-19-05_28PM.txt)

**Comment by griffinpuc** [comment]
Thanks
